# rutas.yml
---
ruta_raíz:
    path:     /
    controller: 'funcionHomePage'
    methods:   [ GET ]

ruta_user_list:
    path:     /api/users
    controller: 'funcionListadoUsuarios'
    methods:
      - GET

ruta_create_user_form:
    path:     /users/create
    controller: 'formCrearUsuario'
    methods:
        - GET

ruta_create_user:
    path:     /api/users
    controller: 'funcionCrearUsuario'
    methods:
        - POST

ruta_user:
    path:     /api/users/{name}
    controller: 'funcionUsuario'
    defaults:
        name: _default_
    methods:
        - GET

ruta_user_delete:
    path:     /api/users/{name}
    controller: 'funcionBorrarUsuario'
    defaults:
        name: _default_
    methods:
        - DELETE

ruta_result_list:
    path:     /api/results
    controller: 'funcionResultados'
    methods:
        - GET

ruta_result:
    path:     /api/results/{name}
    controller: 'funcionResultado'
    defaults:
        name: _default_
    methods:
        - GET