# rutas.yml
---
ruta_raíz:
  path: /
  controller: 'funcionHomePage'
  methods: [ GET ]

ruta_user_list:
  path: /users
  controller: 'funcionListadoUsuarios'
  methods:
    - GET

ruta_create_user_form:
  path: /users/create-form
  controller: 'formCrearUsuario'
  methods:
    - GET

ruta_create_user:
  path: /users
  controller: 'funcionCrearUsuario'
  methods:
    - POST

ruta_update_user_form:
  path: /users/{name}/update-form
  controller: 'formModificarUsuario'
  defaults:
    name: _default_
  methods:
    - GET

ruta_update_user:
  path: /users/{name}/update
  controller: 'funcionModificarUsuario'
  defaults:
    name: _default_
  methods:
    - PUT
    - POST

ruta_user:
  path: /users/{name}
  controller: 'funcionUsuario'
  defaults:
    name: _default_
  methods:
    - GET

ruta_user_delete:
  path: /users/{name}/delete
  controller: 'funcionBorrarUsuario'
  defaults:
    name: _default_
  methods:
    - GET
    - DELETE

ruta_result_list:
  path: /results
  controller: 'funcionResultados'
  methods:
    - GET

ruta_create_result_form:
  path: /results/create-form
  controller: 'formCrearResultado'
  methods:
    - GET

ruta_result:
  path: /results/{name}
  controller: 'funcionResultado'
  defaults:
    name: _default_
  methods:
    - GET

ruta_create_result:
  path: /results
  controller: 'funcionCrearResultado'
  methods:
    - POST

ruta_delete_result:
  path: /results/{name}/delete
  controller: 'funcionBorrarResultado'
  defaults:
    name: _default_
  methods:
    - GET
    - DELETE

ruta_update_result_form:
  path: /results/{name}/update-form
  controller: 'formModificarResultado'
  defaults:
    name: _default_
  methods:
    - GET

ruta_update_result:
  path: /results/{name}/update
  controller: 'funcionModificarResultado'
  defaults:
    name: _default_
  methods:
    - POST
    - PUT